# Generated by Django 4.2.25 on 2025-10-08 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, choices=[('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5')], max_length=2, null=True)),
                ('course', models.ManyToManyField(to='paragliding.course')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('profile_url', 'manager')},
            },
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_url', models.CharField(blank=True, max_length=250, null=True)),
                ('flight_date', models.DateTimeField(blank=True, null=True)),
                ('takeoff_name', models.CharField(blank=True, max_length=50, null=True)),
                ('landing_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_type', models.CharField(blank=True, max_length=50, null=True)),
                ('paraglider', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_olc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('points_olc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_from_takeoff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altitude_takeoff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altitude_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altitude_landing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('flight_url', models.URLField(blank=True, max_length=255, null=True, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_content', models.BinaryField(blank=True, null=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paragliding.pilot')),
            ],
        ),
    ]
