# Generated by Django 5.2.7 on 2025-10-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdata',
            name='pilot',
        ),
        migrations.AddField(
            model_name='flightdata',
            name='pilot',
            field=models.ManyToManyField(to='paragliding.pilot'),
        ),
    ]
