# Generated by Django 5.2.7 on 2025-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdata',
            name='flight_date_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
