# Generated by Django 5.2.7 on 2025-10-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0002_flightdata_flight_date_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='profile_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
