# Generated by Django 5.2.7 on 2025-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0002_remove_flightdata_pilot_flightdata_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdata',
            name='isupdate',
            field=models.BooleanField(default=True),
        ),
    ]
