# Generated by Django 5.2.7 on 2025-10-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0003_flightdata_isupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdata',
            name='pilot',
        ),
        migrations.AddField(
            model_name='flightdata',
            name='pilot_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
