# Generated by Django 5.2.7 on 2025-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragliding', '0003_alter_pilot_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
