# Generated by Django 4.2.25 on 2025-10-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('contentsnippet', models.TextField()),
                ('translated', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('wordpress_id', models.IntegerField(blank=True, null=True)),
                ('wordpress_url', models.CharField(blank=True, max_length=255, null=True)),
                ('isupdate', models.BooleanField()),
                ('cat', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
